/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardWidgetsTablesRouteImport } from './routes/dashboard/widgets/tables'
import { Route as DashboardWidgetsMetricsRouteImport } from './routes/dashboard/widgets/metrics'
import { Route as DashboardWidgetsChartsRouteImport } from './routes/dashboard/widgets/charts'
import { Route as DashboardAuthRegisterRouteImport } from './routes/dashboard/auth/register'
import { Route as DashboardAuthOtpRouteImport } from './routes/dashboard/auth/otp'
import { Route as DashboardAuthLoginRouteImport } from './routes/dashboard/auth/login'
import { Route as DashboardAuthForgotPasswordRouteImport } from './routes/dashboard/auth/forgot-password'
import { Route as DashboardAppsKanbanRouteImport } from './routes/dashboard/apps/kanban'
import { Route as DashboardAppsEmailRouteImport } from './routes/dashboard/apps/email'
import { Route as DashboardManagementCustomersIndexRouteImport } from './routes/dashboard/management/customers/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetsTablesRoute = DashboardWidgetsTablesRouteImport.update({
  id: '/widgets/tables',
  path: '/widgets/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetsMetricsRoute = DashboardWidgetsMetricsRouteImport.update({
  id: '/widgets/metrics',
  path: '/widgets/metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetsChartsRoute = DashboardWidgetsChartsRouteImport.update({
  id: '/widgets/charts',
  path: '/widgets/charts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthRegisterRoute = DashboardAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthOtpRoute = DashboardAuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthLoginRoute = DashboardAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthForgotPasswordRoute =
  DashboardAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppsKanbanRoute = DashboardAppsKanbanRouteImport.update({
  id: '/apps/kanban',
  path: '/apps/kanban',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsEmailRoute = DashboardAppsEmailRouteImport.update({
  id: '/apps/email',
  path: '/apps/email',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManagementCustomersIndexRoute =
  DashboardManagementCustomersIndexRouteImport.update({
    id: '/management/customers/',
    path: '/management/customers/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/apps/email': typeof DashboardAppsEmailRoute
  '/dashboard/apps/kanban': typeof DashboardAppsKanbanRoute
  '/dashboard/auth/forgot-password': typeof DashboardAuthForgotPasswordRoute
  '/dashboard/auth/login': typeof DashboardAuthLoginRoute
  '/dashboard/auth/otp': typeof DashboardAuthOtpRoute
  '/dashboard/auth/register': typeof DashboardAuthRegisterRoute
  '/dashboard/widgets/charts': typeof DashboardWidgetsChartsRoute
  '/dashboard/widgets/metrics': typeof DashboardWidgetsMetricsRoute
  '/dashboard/widgets/tables': typeof DashboardWidgetsTablesRoute
  '/dashboard/management/customers/': typeof DashboardManagementCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/apps/email': typeof DashboardAppsEmailRoute
  '/dashboard/apps/kanban': typeof DashboardAppsKanbanRoute
  '/dashboard/auth/forgot-password': typeof DashboardAuthForgotPasswordRoute
  '/dashboard/auth/login': typeof DashboardAuthLoginRoute
  '/dashboard/auth/otp': typeof DashboardAuthOtpRoute
  '/dashboard/auth/register': typeof DashboardAuthRegisterRoute
  '/dashboard/widgets/charts': typeof DashboardWidgetsChartsRoute
  '/dashboard/widgets/metrics': typeof DashboardWidgetsMetricsRoute
  '/dashboard/widgets/tables': typeof DashboardWidgetsTablesRoute
  '/dashboard/management/customers': typeof DashboardManagementCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/apps/email': typeof DashboardAppsEmailRoute
  '/dashboard/apps/kanban': typeof DashboardAppsKanbanRoute
  '/dashboard/auth/forgot-password': typeof DashboardAuthForgotPasswordRoute
  '/dashboard/auth/login': typeof DashboardAuthLoginRoute
  '/dashboard/auth/otp': typeof DashboardAuthOtpRoute
  '/dashboard/auth/register': typeof DashboardAuthRegisterRoute
  '/dashboard/widgets/charts': typeof DashboardWidgetsChartsRoute
  '/dashboard/widgets/metrics': typeof DashboardWidgetsMetricsRoute
  '/dashboard/widgets/tables': typeof DashboardWidgetsTablesRoute
  '/dashboard/management/customers/': typeof DashboardManagementCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/overview'
    | '/dashboard/'
    | '/dashboard/apps/email'
    | '/dashboard/apps/kanban'
    | '/dashboard/auth/forgot-password'
    | '/dashboard/auth/login'
    | '/dashboard/auth/otp'
    | '/dashboard/auth/register'
    | '/dashboard/widgets/charts'
    | '/dashboard/widgets/metrics'
    | '/dashboard/widgets/tables'
    | '/dashboard/management/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/overview'
    | '/dashboard'
    | '/dashboard/apps/email'
    | '/dashboard/apps/kanban'
    | '/dashboard/auth/forgot-password'
    | '/dashboard/auth/login'
    | '/dashboard/auth/otp'
    | '/dashboard/auth/register'
    | '/dashboard/widgets/charts'
    | '/dashboard/widgets/metrics'
    | '/dashboard/widgets/tables'
    | '/dashboard/management/customers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/overview'
    | '/dashboard/'
    | '/dashboard/apps/email'
    | '/dashboard/apps/kanban'
    | '/dashboard/auth/forgot-password'
    | '/dashboard/auth/login'
    | '/dashboard/auth/otp'
    | '/dashboard/auth/register'
    | '/dashboard/widgets/charts'
    | '/dashboard/widgets/metrics'
    | '/dashboard/widgets/tables'
    | '/dashboard/management/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widgets/tables': {
      id: '/dashboard/widgets/tables'
      path: '/widgets/tables'
      fullPath: '/dashboard/widgets/tables'
      preLoaderRoute: typeof DashboardWidgetsTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widgets/metrics': {
      id: '/dashboard/widgets/metrics'
      path: '/widgets/metrics'
      fullPath: '/dashboard/widgets/metrics'
      preLoaderRoute: typeof DashboardWidgetsMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widgets/charts': {
      id: '/dashboard/widgets/charts'
      path: '/widgets/charts'
      fullPath: '/dashboard/widgets/charts'
      preLoaderRoute: typeof DashboardWidgetsChartsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auth/register': {
      id: '/dashboard/auth/register'
      path: '/auth/register'
      fullPath: '/dashboard/auth/register'
      preLoaderRoute: typeof DashboardAuthRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auth/otp': {
      id: '/dashboard/auth/otp'
      path: '/auth/otp'
      fullPath: '/dashboard/auth/otp'
      preLoaderRoute: typeof DashboardAuthOtpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auth/login': {
      id: '/dashboard/auth/login'
      path: '/auth/login'
      fullPath: '/dashboard/auth/login'
      preLoaderRoute: typeof DashboardAuthLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auth/forgot-password': {
      id: '/dashboard/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/dashboard/auth/forgot-password'
      preLoaderRoute: typeof DashboardAuthForgotPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apps/kanban': {
      id: '/dashboard/apps/kanban'
      path: '/apps/kanban'
      fullPath: '/dashboard/apps/kanban'
      preLoaderRoute: typeof DashboardAppsKanbanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apps/email': {
      id: '/dashboard/apps/email'
      path: '/apps/email'
      fullPath: '/dashboard/apps/email'
      preLoaderRoute: typeof DashboardAppsEmailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/management/customers/': {
      id: '/dashboard/management/customers/'
      path: '/management/customers'
      fullPath: '/dashboard/management/customers/'
      preLoaderRoute: typeof DashboardManagementCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppsEmailRoute: typeof DashboardAppsEmailRoute
  DashboardAppsKanbanRoute: typeof DashboardAppsKanbanRoute
  DashboardAuthForgotPasswordRoute: typeof DashboardAuthForgotPasswordRoute
  DashboardAuthLoginRoute: typeof DashboardAuthLoginRoute
  DashboardAuthOtpRoute: typeof DashboardAuthOtpRoute
  DashboardAuthRegisterRoute: typeof DashboardAuthRegisterRoute
  DashboardWidgetsChartsRoute: typeof DashboardWidgetsChartsRoute
  DashboardWidgetsMetricsRoute: typeof DashboardWidgetsMetricsRoute
  DashboardWidgetsTablesRoute: typeof DashboardWidgetsTablesRoute
  DashboardManagementCustomersIndexRoute: typeof DashboardManagementCustomersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppsEmailRoute: DashboardAppsEmailRoute,
  DashboardAppsKanbanRoute: DashboardAppsKanbanRoute,
  DashboardAuthForgotPasswordRoute: DashboardAuthForgotPasswordRoute,
  DashboardAuthLoginRoute: DashboardAuthLoginRoute,
  DashboardAuthOtpRoute: DashboardAuthOtpRoute,
  DashboardAuthRegisterRoute: DashboardAuthRegisterRoute,
  DashboardWidgetsChartsRoute: DashboardWidgetsChartsRoute,
  DashboardWidgetsMetricsRoute: DashboardWidgetsMetricsRoute,
  DashboardWidgetsTablesRoute: DashboardWidgetsTablesRoute,
  DashboardManagementCustomersIndexRoute:
    DashboardManagementCustomersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
